apiVersion: lib.projectsveltos.io/v1beta1
kind: HealthCheck
metadata:
 name: depl-replicas
spec:
  resourceSelectors: 
  - group: apps
    version: v1
    kind: Deployment
  evaluateHealth: |
    function evaluate()
      local statuses = {}

      for _,resource in ipairs(resources) do
        local status = {}
        local message = ""
        if resource.status ~= nil then
          if resource.status.availableReplicas ~= nil then
            if resource.status.availableReplicas == resource.spec.replicas then
              status = "Healthy"
            end
            if resource.status.availableReplicas ~= resource.spec.replicas then
              message = "expected replicas: " .. resource.spec.replicas .. " available: " .. resource.status.availableReplicas
              status = "Progressing"
            end
          end

          if resource.status.unavailableReplicas ~= nil then
            if resource.status.unavailableReplicas ~= 0 then
              status = "Degraded"
              message = "replicas are unavailable"
            end
          end
        else
          status = "Progressing"
        end

        table.insert(statuses, {resource=resource, status = status, message = message})
      end

      local hs = {}
      if #statuses > 0 then
        hs.resources = statuses 
      end
      return hs
    end