apiVersion: lib.projectsveltos.io/v1alpha1
kind: HealthCheck
metadata:
 name: pod-not-ready
spec:
 collectResources: true
 group: ""
 version: v1
 kind: Node
 script: |
  function evaluate()
    hs = {}
    hs.status = "Healthy"
    hs.ignore = false

    local isKubeletReady = false
    local conditions = obj.status.conditions
    if conditions then
      for _, condition in ipairs(conditions) do
        if condition.type == "Ready" and condition.status == "True" then
          isKubeletReady = true
          break
        end
      end
    end

    if not isKubeletReady then
      hs.status = "Degraded"
    end

    return hs
  end

