apiVersion: v1
kind: Service
metadata:
  name: another-service
  namespace: default
  labels:
    sveltos: fv
spec:
  selector:
    app.kubernetes.io/name: MyApp-secure
  ports:
    - protocol: TCP
      port: 443
      targetPort: 9376