apiVersion: v1
kind: Service
metadata:
  name: non-matching
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9376
